const links={appBarber:"https://sites.appbarber.com.br/demo-navalha-prime",whatsappBarbearia:"https://wa.me/5519999900000?text=Olá,%20quero%20agendar%20meu%20horário.",whatsappOlegarioTech:"https://wa.me/5519974059590?text=Olá,%20Alexandre.%20Quero%20uma%20experiência%20premium%20como%20a%20demo%20de%20barbearia.",maps:"https://www.google.com/maps/search/?api=1&query=Valinhos%20SP"};
const services=[{category:"Mais pedidos",title:"Corte Masculino Premium",duration:"35 min",price:"R$ 65",icon:"✂",description:"Corte alinhado, acabamento limpo e finalização com presença.",cta:"Agendar corte"},{category:"Mais pedidos",title:"Barba com Toalha Quente",duration:"35 min",price:"R$ 65",icon:"♨",description:"Barba desenhada, navalha precisa e ritual de cuidado masculino.",cta:"Agendar barba"},{category:"Combo premium",title:"Cabelo + Barba",duration:"60 min",price:"R$ 130",icon:"◆",description:"Visual completo para sair da cadeira pronto para dominar o dia.",cta:"Agendar combo"},{category:"Recorrência",title:"Plano Sempre Alinhado",duration:"Mensal",price:"A partir de R$ 120/mês",icon:"∞",description:"Assinatura para manter agenda, visual e presença sempre em dia.",cta:"Ver planos"}];
const barbers=[{name:"Rafael Torres",specialty:"Degradê navalhado e corte moderno",initials:"RT",tags:["Degradê","Freestyle","Acabamento"],highlight:"Mais procurado"},{name:"Bruno Almeida",specialty:"Barba premium e toalha quente",initials:"BA",tags:["Barba","Navalha","Combo"],highlight:"Barba clássica"},{name:"Diego Martins",specialty:"Corte social e executivo",initials:"DM",tags:["Executivo","Social","Agenda rápida"],highlight:"Executivo"},{name:"Caio Nogueira",specialty:"Infantil, moderno e desenho",initials:"CN",tags:["Kids","Desenho","Moderno"],highlight:"Família"},{name:"Lucas Ferraz",specialty:"Pigmentação e transformação visual",initials:"LF",tags:["Pigmentação","Luzes","Transformação"],highlight:"Transformação"}];
const plans=[{name:"Essencial",price:"R$ 55/mês",description:"1 corte por mês para manter o visual sempre controlado.",features:["1 corte mensal","Agenda facilitada","Lembrete no WhatsApp"]},{name:"Barba Alinhada",price:"R$ 150/mês",description:"Para quem cuida da barba como assinatura de presença.",features:["Barba recorrente","Toalha quente","Prioridade na agenda"]},{name:"Prime Combo",price:"R$ 210/mês",description:"Cabelo e barba com recorrência para visual sempre premium.",features:["Corte + barba","Benefício recorrente","Atendimento premium"],featured:true}];
const testimonials=[{name:"Cliente demo",text:"Agendei em menos de um minuto. Escolhi barbeiro, serviço e horário sem precisar ficar perguntando no WhatsApp."},{name:"Cliente demo",text:"O site passa outra sensação. Antes de chegar na barbearia, eu já senti que era uma experiência premium."},{name:"Cliente demo",text:"A assinatura resolveu minha rotina. Todo mês eu já sei quando vou cortar e manter o visual alinhado."}];
const units=[{name:"Navalha Prime — Centro",address:"Rua Barão do Café, 188 — Centro — Valinhos/SP",hours:"Seg. a sex.: 09h às 20h • Sáb.: 08h às 16h"},{name:"Navalha Prime — Jardim Aurora",address:"Av. das Palmeiras, 742 — Jardim Aurora — Valinhos/SP",hours:"Seg. a sex.: 10h às 21h • Sáb.: 08h às 17h"}];
const $=(s,scope=document)=>scope.querySelector(s);const $$=(s,scope=document)=>Array.from(scope.querySelectorAll(s));
function applyLinks(){$$("[data-link]").forEach(el=>{const key=el.dataset.link;if(links[key]){el.href=links[key];el.target="_blank";el.rel="noopener noreferrer"}})}
function renderServices(){const grid=$("#servicesGrid");grid.innerHTML=services.map(s=>`<article class="card reveal"><div class="card-visual">${s.icon}</div><div class="card-body"><span class="category">${s.category}</span><h3>${s.title}</h3><div class="meta"><strong>${s.price}</strong><span>${s.duration}</span></div><p class="copy">${s.description}</p><a class="card-link" data-link="appBarber" href="#">${s.cta} →</a></div></article>`).join("")}
function renderBarbers(){const track=$("#barbersTrack");track.innerHTML=barbers.map(b=>`<article class="barber reveal"><span class="highlight">${b.highlight}</span><div class="barber-visual">${b.initials}</div><div class="barber-info"><h3>${b.name}</h3><p class="copy">${b.specialty}</p><div class="tags">${b.tags.map(t=>`<span>${t}</span>`).join("")}</div><a class="card-link" data-link="appBarber" href="#">Agendar com ${b.name.split(" ")[0]} →</a></div></article>`).join("")}
function renderPlans(){const grid=$("#plansGrid");grid.innerHTML=plans.map(p=>`<article class="plan reveal ${p.featured?"featured":""}"><h3>${p.name}</h3><div class="price">${p.price}</div><p class="copy">${p.description}</p><ul>${p.features.map(f=>`<li>${f}</li>`).join("")}</ul><a class="card-link" data-link="appBarber" href="#">Assinar pelo app →</a></article>`).join("")}
function renderTestimonials(){const grid=$("#testimonialsGrid");grid.innerHTML=testimonials.map(t=>`<article class="testimonial reveal"><strong>${t.name}</strong><p class="copy">“${t.text}”</p></article>`).join("")}
function renderUnits(){const grid=$("#unitsGrid");grid.innerHTML=units.map(u=>`<article class="unit reveal"><span class="category">Unidade demo</span><h3>${u.name}</h3><p class="copy">${u.address}</p><p class="copy">${u.hours}</p><a class="card-link" data-link="appBarber" href="#">Agendar nessa unidade →</a><br><a class="card-link" href="${links.maps}" target="_blank" rel="noopener noreferrer">Como chegar →</a></article>`).join("")}
function renderBookingChoices(){const serviceChoices=$("#serviceChoices");const barberChoices=$("#barberChoices");serviceChoices.innerHTML=["Corte","Barba","Combo","Planos"].map((item,i)=>`<button class="choice ${i===0?"selected":""}" data-next-step="2">${item}</button>`).join("");barberChoices.innerHTML=barbers.slice(0,4).map((b,i)=>`<button class="choice ${i===0?"selected":""}" data-next-step="3">${b.name.split(" ")[0]}</button>`).join("")}
function setupBookingSteps(){$$(".choice[data-next-step]").forEach(button=>{button.addEventListener("click",()=>{const parent=button.closest(".choice-grid");$$(".choice",parent).forEach(item=>item.classList.remove("selected"));button.classList.add("selected");setTimeout(()=>{$$(".booking-step").forEach(step=>step.classList.remove("active"));$(`.booking-step[data-step="${button.dataset.nextStep}"]`).classList.add("active")},160)})})}
function setupHeader(){const header=$("#header");const progress=$("#progress");window.addEventListener("scroll",()=>{const top=window.scrollY;const h=document.body.scrollHeight-window.innerHeight;header.classList.toggle("is-scrolled",top>40);progress.style.width=`${h>0?top/h*100:0}%`},{passive:true})}
function setupSmoothScroll(){if(!window.Lenis)return;const lenis=new Lenis({duration:1.08,smoothWheel:true,wheelMultiplier:.85});function raf(time){lenis.raf(time);requestAnimationFrame(raf)}requestAnimationFrame(raf)}
function setupAnimations(){if(!window.gsap||!window.ScrollTrigger){$$(".reveal").forEach(el=>{el.style.opacity=1;el.style.transform="none"});return}gsap.registerPlugin(ScrollTrigger);gsap.to(".preloader-mark",{scale:1.04,duration:.9,repeat:-1,yoyo:true,ease:"power1.inOut"});gsap.utils.toArray(".reveal").forEach(el=>{gsap.to(el,{opacity:1,y:0,duration:.85,ease:"power3.out",scrollTrigger:{trigger:el,start:"top 86%"}})});gsap.to(".razor-line",{xPercent:-28,yPercent:12,ease:"none",scrollTrigger:{trigger:".hero",start:"top top",end:"bottom top",scrub:true}});gsap.utils.toArray(".magnetic").forEach(el=>{el.addEventListener("mousemove",event=>{const rect=el.getBoundingClientRect();const x=event.clientX-rect.left-rect.width/2;const y=event.clientY-rect.top-rect.height/2;gsap.to(el,{x:x*.12,y:y*.18,duration:.35,ease:"power3.out"})});el.addEventListener("mouseleave",()=>gsap.to(el,{x:0,y:0,duration:.55,ease:"elastic.out(1,.4)"}))})}
function setupPreloader(){const preloader=$("#preloader");window.addEventListener("load",()=>setTimeout(()=>preloader.classList.add("is-hidden"),550))}
function init(){renderServices();renderBarbers();renderPlans();renderTestimonials();renderUnits();renderBookingChoices();applyLinks();setupBookingSteps();setupHeader();setupSmoothScroll();setupAnimations();setupPreloader()}init();
